---

#// user account used to ssh the hosts
remote_user: ubuntu
docker_group: docker
github_repo: 'https://github.com/dbjpanda/drupal-devops.git'
staging_branch: 'develop'
env_file: 'develop'
backup_dir: '/var/www/docker'
project_dir: '/var/www/html'
project_folder_name: 'drupal8'
backup_folder_name: 'ansible-backup'